Update Build Android Dropbear.yml

diff --git a/.github/workflows/Build Android Dropbear.yml b/.github/workflows/Build Android Dropbear.yml
--- a/.github/workflows/Build Android Dropbear.yml
+++ b/.github/workflows/Build Android Dropbear.yml
@@ -32,14 +32,7 @@ jobs:
         echo "NDK_HOME=$HOME/android-ndk-r11c" >> $GITHUB_ENV
         echo "PATH=$HOME/android-ndk-r11c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV
 
-    # Run configure script
-    - name: Run configure script
-      run: |
-        cd dropbear-android
-        chmod +x configure
-        ./configure || true  # 忽略非零退出码，继续执行
-
-    # Locate options.h and modify it if it exists
+    # Locate options.h and modify it if exists
     - name: Modify options.h if it exists
       run: |
         cd dropbear-android
@@ -57,7 +50,7 @@ jobs:
       run: |
         cd dropbear-android
         chmod +x build.sh
-        ./build.sh || true  # 如果 build.sh 返回非零退出码，继续执行
+        ./build.sh || true  # Ignore non-zero exit code and continue
 
     # Upload the compiled binary as an artifact
     - name: Upload binary
